import { message, type MessageDictionary } from './Locale';
// Stable keys belong to UI content, independently of username, room name or save identity.
const rows = [
 ['journey','Begin your journey','Bắt đầu hành trình'],['selected','Selected','Đã chọn'],
 ['login','Sign in','Đăng nhập'],['eyebrow','EXPLORE · BUILD · BELONG','KHÁM PHÁ · XÂY DỰNG · GẮN BÓ'],
 ['heading','One world. Your footprints.','Một thế giới. Dấu chân của bạn.'],
 ['pitch','Land among floating islands. Build your first base and discover what waits beyond the fog.','Hạ cánh giữa những mảnh đất lơ lửng. Dựng căn cứ đầu tiên và tìm điều gì đang chờ phía sau màn sương.'],
 ['modes','Game modes','Chế độ chơi'],['single','Single Player','Chơi đơn'],['multi','Multiplayer','Nhiều người chơi'],['skin','Appearance','Trang phục'],
 ['note','Alone or with up to two friends.','Một mình hoặc cùng tối đa hai người bạn.'],['fullscreen','Fullscreen','Toàn màn hình'],['fullscreenDenied','The browser has not allowed fullscreen.','Trình duyệt chưa cho phép toàn màn hình'],
 ['connectionError','Cannot connect. Try again.','Không thể kết nối, thử lại'],['processing','Working…','Đang xử lý…'],['retry','Try again later','Thử lại sau'],['continueCoop','Continue saved co-op world','Tiếp tục thế giới co-op đã lưu'],
 ['register','Create account','Tạo tài khoản'],['recover','Recover account','Khôi phục tài khoản'],['accountHelp','Save your appearance and manage your rooms.','Lưu skin và quản lý phòng chơi của bạn.'],['recoveryHelp','Use the recovery code received when you created your account.','Dùng mã khôi phục đã nhận khi tạo tài khoản.'],
 ['username','Username','Tên đăng nhập'],['newPassword','New password','Mật khẩu mới'],['password','Password','Mật khẩu'],['passwordHelp','Account passwords need at least 15 characters.','Mật khẩu tài khoản cần ít nhất 15 ký tự.'],['recoveryCode','Recovery code','Mã khôi phục'],['resetPassword','Reset password','Đặt lại mật khẩu'],
 ['recoveryNotice','Keep this code to recover a forgotten password. Do not share it.','Lưu mã này để khôi phục khi quên mật khẩu. Không chia sẻ với người khác.'],['downloadCode','Download recovery code','Tải mã khôi phục'],['codeSaved','I saved the code · Continue','Tôi đã lưu mã · Tiếp tục'],['newAccount','Create a new account','Tạo tài khoản mới'],['existingAccount','Already have an account','Đã có tài khoản'],['forgotPassword','Forgot password','Quên mật khẩu'],
 ['createRoom','Create room','Tạo phòng'],['manageRoom','Manage room','Quản lý phòng'],['joinRoom','Join room','Vào phòng'],['editRoomHelp','Change the name or passcode. World progress is preserved.','Đổi tên hoặc mật mã. Tiến độ thế giới vẫn được giữ.'],['roomHelp','A private room for you and up to two friends.','Phòng riêng cho bạn và tối đa hai người bạn.'],['roomName','Room name','Tên phòng'],['optionalPassword','New passcode (leave blank to keep it)','Mật mã mới (để trống nếu giữ nguyên)'],['roomPassword','Room passcode','Mật mã phòng'],['createAndJoin','Create room and play','Tạo phòng và vào game'],['saveChanges','Save changes','Lưu thay đổi'],['play','Play','Vào game'],['roomUpdated','Room updated','Đã cập nhật phòng'],['back','Back','Quay lại'],['deleteRoom','Delete room','Xóa phòng'],['deleteConfirm','Permanently delete this world? Export an in-game backup first and have everyone leave the room.','Xóa vĩnh viễn thế giới này? Xuất bản sao lưu trong game trước và để mọi người rời phòng.'],['roomDeleted','Room deleted','Đã xóa phòng'],
 ['coopHeading','Explore ProZ0 together','Cùng nhau đặt chân đến ProZ0'],['coopHelp','Create a room with a name and passcode, or join a friend’s room.','Tạo phòng bằng tên và mật mã, hoặc vào phòng của bạn bè.'],['coopLogin','Sign in to play multiplayer','Đăng nhập để chơi Multiplayer'],['joinByName','Join by room name','Vào bằng tên phòng'],['rooms','Rooms','Danh sách phòng'],['noRooms','No rooms yet. Create one to begin with friends.','Chưa có phòng. Tạo một phòng để bắt đầu cùng bạn bè.'],['ownedRoom','Your room · up to 3 players','Phòng của bạn · tối đa 3 người'],['privateRoom','Private room · up to 3 players','Phòng riêng · tối đa 3 người'],['continue','Continue','Tiếp tục'],['manage','Manage','Quản lý'],
 ['soloHelp','Begin your own journey. Progress is saved in this browser.','Bắt đầu hành trình của riêng bạn. Tiến độ được lưu trong trình duyệt này.'],['seed','World seed · leave blank for a random world','Seed thế giới · để trống để tạo ngẫu nhiên'],['seedExample','Example: mist-expedition-01','Ví dụ: mist-expedition-01'],['continueSolo','Continue world','Tiếp tục thế giới'],['upgrade','Upgrade Colony world','Nâng cấp thế giới Colony'],['start','Start a new world','Bắt đầu thế giới mới'],
 ['skinHelp','Choose an outfit for your expedition. Appearance only changes visuals.','Chọn bộ đồ cho chuyến thám hiểm. Trang phục chỉ thay đổi hình ảnh.'],['skinLocal','Your appearance is saved on this device. Sign in to save it to your account.','Trang phục hiện lưu trên thiết bị này. Đăng nhập để lưu theo tài khoản.'],['account','Your account','Tài khoản của bạn'],['displayName','Room display name','Tên hiển thị trong phòng'],['saveName','Save display name','Lưu tên hiển thị'],['chooseSkin','Choose appearance','Chọn trang phục'],['logout','Sign out','Đăng xuất'],['keepCode','Keep your recovery code','Giữ mã khôi phục'],['accountReady','Your account is ready.','Tài khoản đã sẵn sàng.'],
 ['loginHelp','Single-player is ready to play; multiplayer uses your account.','Single Player có thể chơi ngay; Multiplayer dùng tài khoản của bạn.'],
 ['seedHelp','The same seed creates the same initial terrain and resources. New worlds have separate saves; Continue preserves their seed and progress.','Cùng seed tạo cùng địa hình và tài nguyên ban đầu. Mỗi thế giới mới có bản lưu riêng; Tiếp tục giữ nguyên seed và tiến độ.'],
 ['nameSaved','Display name saved; it applies when you rejoin the room.','Đã lưu tên hiển thị; áp dụng khi vào lại phòng.'],
] as const;
export const lobbyMessages: MessageDictionary = { en: Object.fromEntries(rows.map(([key,en])=>[key,en])), vi:Object.fromEntries(rows.map(([key,,vi])=>[key,vi])) };
export const lobbyText = (key:string) => message(lobbyMessages,key);
export const lobbySourceKeys = Object.fromEntries(rows.flatMap(([key,en,vi])=>[[en,key],[vi,key]]));
