import { expect, test } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { walk } from './support/solo-actions';

test('resource sizes: explicit inspection yield matches actual harvest and survives save/reopen', async ({ page }) => {
  test.setTimeout(120000);
  await page.goto('/?proz0Mode=phase2-colony-review&proz0WorldId=world:size-ui&proz0WorldSeed=p1-world-golden&proz0Players=solo&proz0Player=solo&proz0SaveDb=size-ui');
  await expect(page.locator('[data-proz0-autoboot]')).toHaveAttribute('data-runtime-status', 'ready');
  const quantity = async () => {
    await page.keyboard.press('i');
    const row = page.locator('[data-panel-kind="inventory"]').getByRole('button', { name: 'Plant Fiber', exact: true });
    const n = await row.count() ? Number((await row.textContent())?.match(/×(\d+)/)?.[1]) : 0;
    await page.keyboard.press('Escape'); return n;
  };
  const before = await quantity();
  await walk(page, 18, 10);
  const target = page.locator('[data-world-role="resource"][data-focused-target="true"]');
  await expect(target).toHaveAttribute('aria-label', 'Gather Fiber Plant');
  const identity = await target.getAttribute('data-world-id'), size = await target.getAttribute('data-resource-size');
  expect(['small', 'medium', 'large']).toContain(size);
  await expect(target).not.toHaveAttribute('title');
  await target.click({button:'right'});
  const inspection = page.getByRole('region',{name:'Entity statistics',exact:true});
  await expect(inspection).toContainText('Fiber Plant');
  const yieldCount = Number((await inspection.innerText()).match(/Yield: (\d+) Plant Fiber/)?.[1]); expect(yieldCount).toBeGreaterThan(0);
  await expect(page.locator('[data-region="interaction"]')).not.toHaveAttribute('data-state','CHANNELING');
  const box = await inspection.boundingBox(); expect(box!.width).toBeLessThanOrEqual(320);expect(box!.height).toBeLessThanOrEqual(280);
  mkdirSync('test-results/entity-inspection', { recursive: true });
  await page.screenshot({ path: 'test-results/entity-inspection/desktop.png' });
  await page.setViewportSize({ width: 640, height: 360 });
  await expect(inspection).toBeVisible();
  const compactBox = await inspection.boundingBox();
  expect(compactBox!.x).toBeGreaterThanOrEqual(0);
  expect(compactBox!.x + compactBox!.width).toBeLessThanOrEqual(640);
  expect(compactBox!.height).toBeLessThanOrEqual(162);
  await page.screenshot({ path: 'test-results/entity-inspection/compact.png' });
  await page.keyboard.press('Escape');
  await expect(inspection).toBeHidden();
  await target.focus(); await page.keyboard.press('Shift+F10');
  await expect(inspection).toBeVisible();
  await page.keyboard.press('m');
  await expect(inspection).toBeHidden();
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 1280, height: 720 });
  await target.click();
  await expect(inspection).toBeHidden();
  const interaction = page.locator('[data-region="interaction"]');
  await expect(interaction).toHaveAttribute('data-state', 'CHANNELING');
  await expect(interaction).toHaveAttribute('data-state', 'AVAILABLE', { timeout: 5000 });
  expect(await quantity()).toBe(before + yieldCount);
  mkdirSync('test-results/resource-size', { recursive: true });
  await page.screenshot({ path: 'test-results/resource-size/world.png' });
  await page.keyboard.press('l'); await expect(page.locator('[data-product-review-save]')).toHaveAttribute('data-save-state', 'success');
  await page.reload(); await expect(page.locator('[data-proz0-autoboot]')).toHaveAttribute('data-runtime-status', 'ready');
  await expect(page.locator('[data-world-id="' + identity + '"][data-world-role="resource"]')).toHaveAttribute('data-resource-size', size!);
  expect(await quantity()).toBe(before + yieldCount);
});
