import {
  CONTENT_FORMAT_ID,
  CONTENT_SCHEMA_VERSION,
  PHASE1_CONTENT_PACK_ID,
  PHASE1_CONTENT_PACK_VERSION,
  type ContentDefinitionV1,
  type ContentPackV1,
  type ItemDefinitionV1,
  type ItemQuantitySpecV1,
  type MilestoneXpRuleV1,
  type RecipeDefinitionV1,
  type RepeatXpRuleV1,
  type ResourceNodeDefinitionV1,
} from '../SchemaV1';

function item(
  definition: Omit<ItemDefinitionV1, 'kind' | 'ordinaryStorageAllowed'>,
): ItemDefinitionV1 {
  return {
    kind: 'item',
    ordinaryStorageAllowed: true,
    ...definition,
  };
}

function quantity(
  itemId: string,
  amount: number,
  initialCondition?: number,
): ItemQuantitySpecV1 {
  return {
    itemId,
    quantity: amount,
    ...(initialCondition === undefined ? {} : { initialCondition }),
  };
}

function recipe(
  definition: Omit<RecipeDefinitionV1, 'kind'>,
): RecipeDefinitionV1 {
  return {
    kind: 'recipe',
    ...definition,
  };
}

function resource(
  definition: Omit<ResourceNodeDefinitionV1, 'kind'>,
): ResourceNodeDefinitionV1 {
  return {
    kind: 'resource',
    ...definition,
  };
}

function milestone(
  id: string,
  trigger: MilestoneXpRuleV1['trigger'],
  xp: number,
): MilestoneXpRuleV1 {
  return {
    id,
    trigger,
    xp,
    lifetimeScope: 'per-player-world',
  };
}

function repeat(
  id: string,
  triggerType: RepeatXpRuleV1['triggerType'],
  xpPerRewardedAction: number,
  maxRewardedActions: number,
): RepeatXpRuleV1 {
  return {
    id,
    triggerType,
    xpPerRewardedAction,
    maxRewardedActions,
    lifetimeScope: 'per-player-world',
  };
}

const DEFINITIONS: readonly ContentDefinitionV1[] = [
  item({
    id: 'item:plant-fiber',
    displayName: 'Plant Fiber',
    category: 'raw-resource',
    unitWeightKg: 0.05,
    unitVolume: 0.10,
    maxStack: 50,
    conditionMax: null,
    capabilities: [],
  }),
  item({
    id: 'item:timber',
    displayName: 'Timber',
    category: 'raw-resource',
    unitWeightKg: 1,
    unitVolume: 2,
    maxStack: 10,
    conditionMax: null,
    capabilities: [],
  }),
  item({
    id: 'item:stone',
    displayName: 'Stone',
    category: 'raw-resource',
    unitWeightKg: 0.75,
    unitVolume: 0.75,
    maxStack: 20,
    conditionMax: null,
    capabilities: [],
  }),
  item({
    id: 'item:metal-ore',
    displayName: 'Metal Ore',
    category: 'raw-resource',
    unitWeightKg: 1,
    unitVolume: 0.75,
    maxStack: 20,
    conditionMax: null,
    capabilities: [],
  }),
  item({
    id: 'item:edible-plant',
    displayName: 'Edible Plant',
    category: 'food',
    unitWeightKg: 0.20,
    unitVolume: 0.25,
    maxStack: 10,
    conditionMax: null,
    capabilities: ['consumable', 'usable'],
    useProfile: {
      type: 'restore-stat',
      stat: 'food',
      amount: 20,
      channelSeconds: 1,
    },
  }),
  item({
    id: 'item:clean-water',
    displayName: 'Clean Water',
    category: 'water',
    unitWeightKg: 0.50,
    unitVolume: 0.50,
    maxStack: 10,
    conditionMax: null,
    capabilities: ['consumable', 'usable'],
    useProfile: {
      type: 'restore-stat',
      stat: 'water',
      amount: 25,
      channelSeconds: 1,
    },
  }),
  item({
    id: 'item:cordage',
    displayName: 'Cordage',
    category: 'component',
    unitWeightKg: 0.10,
    unitVolume: 0.20,
    maxStack: 20,
    conditionMax: null,
    capabilities: [],
  }),
  item({
    id: 'item:stone-field-tool',
    displayName: 'Stone Field Tool',
    category: 'tool',
    unitWeightKg: 1.50,
    unitVolume: 2,
    maxStack: 1,
    conditionMax: 100,
    capabilities: ['equippable', 'usable', 'gather-tool'],
  }),
  item({
    id: 'item:basic-spear',
    displayName: 'Basic Spear',
    category: 'weapon',
    unitWeightKg: 1.80,
    unitVolume: 2.50,
    maxStack: 1,
    conditionMax: 100,
    capabilities: ['equippable', 'usable', 'melee-weapon'],
    useProfile: {
      type: 'melee-weapon',
      rangeFootprints: 1.5,
      frontalArcDegrees: 90,
      staminaCost: 15,
      damage: 25,
      cooldownSeconds: 0.65,
      conditionCostOnSuccessfulHit: 1,
    },
  }),
  item({
    id: 'item:thermal-wrap',
    displayName: 'Thermal Wrap',
    category: 'equipment',
    unitWeightKg: 1,
    unitVolume: 2,
    maxStack: 1,
    conditionMax: 100,
    capabilities: ['equippable', 'thermal-equipment'],
    useProfile: {
      type: 'thermal-protection',
      harmfulThermalRateMultiplier: 0.5,
    },
  }),
  item({
    id: 'item:field-dressing',
    displayName: 'Field Dressing',
    category: 'medical',
    unitWeightKg: 0.20,
    unitVolume: 0.20,
    maxStack: 10,
    conditionMax: null,
    capabilities: ['consumable', 'usable'],
    useProfile: {
      type: 'restore-stat',
      stat: 'health',
      amount: 30,
      channelSeconds: 1,
    },
  }),
  item({
    id: 'item:repair-patch',
    displayName: 'Repair Patch',
    category: 'component',
    unitWeightKg: 0.25,
    unitVolume: 0.30,
    maxStack: 10,
    conditionMax: null,
    capabilities: [],
  }),
  item({
    id: 'item:storage-crate-kit',
    displayName: 'Storage Crate Kit',
    category: 'construction-kit',
    unitWeightKg: 5,
    unitVolume: 6,
    maxStack: 1,
    conditionMax: null,
    capabilities: ['usable', 'construction-kit'],
  }),
  item({
    id: 'item:workbench-kit',
    displayName: 'Workbench Kit',
    category: 'construction-kit',
    unitWeightKg: 8,
    unitVolume: 8,
    maxStack: 1,
    conditionMax: null,
    capabilities: ['usable', 'construction-kit'],
  }),
  item({
    id: 'item:habitat-kit',
    displayName: 'Habitat Kit',
    category: 'construction-kit',
    unitWeightKg: 12,
    unitVolume: 12,
    maxStack: 1,
    conditionMax: null,
    capabilities: ['usable', 'construction-kit'],
  }),
  item({
    id: 'item:power-unit-kit',
    displayName: 'Power Unit Kit',
    category: 'construction-kit',
    unitWeightKg: 10,
    unitVolume: 8,
    maxStack: 1,
    conditionMax: null,
    capabilities: ['usable', 'construction-kit'],
  }),
  item({
    id: 'item:machine-kit',
    displayName: 'Machine Kit',
    category: 'construction-kit',
    unitWeightKg: 10,
    unitVolume: 10,
    maxStack: 1,
    conditionMax: null,
    capabilities: ['usable', 'construction-kit'],
  }),
  item({
    id: 'item:ancient-alloy-shard',
    displayName: 'Ancient Alloy Shard',
    category: 'discovery-item',
    unitWeightKg: 2,
    unitVolume: 2,
    maxStack: 1,
    conditionMax: null,
    capabilities: ['discovery-reward'],
  }),

  recipe({
    id: 'recipe:cordage',
    displayName: 'Cordage',
    tier: 'hand',
    requiredStationStructureId: null,
    inputs: [quantity('item:plant-fiber', 3)],
    outputs: [quantity('item:cordage', 1)],
  }),
  recipe({
    id: 'recipe:stone-field-tool',
    displayName: 'Stone Field Tool',
    tier: 'hand',
    requiredStationStructureId: null,
    inputs: [
      quantity('item:timber', 1),
      quantity('item:stone', 2),
      quantity('item:cordage', 1),
    ],
    outputs: [quantity('item:stone-field-tool', 1, 100)],
  }),
  recipe({
    id: 'recipe:basic-spear',
    displayName: 'Basic Spear',
    tier: 'hand',
    requiredStationStructureId: null,
    inputs: [
      quantity('item:timber', 2),
      quantity('item:stone', 1),
      quantity('item:cordage', 1),
    ],
    outputs: [quantity('item:basic-spear', 1, 100)],
  }),
  recipe({
    id: 'recipe:thermal-wrap',
    displayName: 'Thermal Wrap',
    tier: 'hand',
    requiredStationStructureId: null,
    inputs: [
      quantity('item:plant-fiber', 5),
      quantity('item:cordage', 2),
    ],
    outputs: [quantity('item:thermal-wrap', 1, 100)],
  }),
  recipe({
    id: 'recipe:field-dressing',
    displayName: 'Field Dressing',
    tier: 'hand',
    requiredStationStructureId: null,
    inputs: [quantity('item:plant-fiber', 4)],
    outputs: [quantity('item:field-dressing', 1)],
  }),
  recipe({
    id: 'recipe:storage-crate-kit',
    displayName: 'Storage Crate Kit',
    tier: 'hand',
    requiredStationStructureId: null,
    inputs: [
      quantity('item:timber', 4),
      quantity('item:cordage', 2),
    ],
    outputs: [quantity('item:storage-crate-kit', 1)],
  }),
  recipe({
    id: 'recipe:workbench-kit',
    displayName: 'Workbench Kit',
    tier: 'hand',
    requiredStationStructureId: null,
    inputs: [
      quantity('item:timber', 4),
      quantity('item:stone', 4),
      quantity('item:cordage', 2),
    ],
    outputs: [quantity('item:workbench-kit', 1)],
  }),
  recipe({
    id: 'recipe:repair-patch',
    displayName: 'Repair Patch',
    tier: 'workbench',
    requiredStationStructureId: 'structure:workbench',
    inputs: [
      quantity('item:plant-fiber', 2),
      quantity('item:metal-ore', 1),
    ],
    outputs: [quantity('item:repair-patch', 1)],
  }),
  recipe({
    id: 'recipe:habitat-kit',
    displayName: 'Habitat Kit',
    tier: 'workbench',
    requiredStationStructureId: 'structure:workbench',
    inputs: [
      quantity('item:timber', 6),
      quantity('item:stone', 6),
      quantity('item:cordage', 3),
    ],
    outputs: [quantity('item:habitat-kit', 1)],
  }),
  recipe({
    id: 'recipe:power-unit-kit',
    displayName: 'Power Unit Kit',
    tier: 'workbench',
    requiredStationStructureId: 'structure:workbench',
    inputs: [
      quantity('item:timber', 4),
      quantity('item:metal-ore', 5),
      quantity('item:cordage', 2),
    ],
    outputs: [quantity('item:power-unit-kit', 1)],
  }),
  recipe({
    id: 'recipe:machine-kit',
    displayName: 'Machine Kit',
    tier: 'workbench',
    requiredStationStructureId: 'structure:workbench',
    inputs: [
      quantity('item:timber', 4),
      quantity('item:metal-ore', 6),
      quantity('item:cordage', 3),
    ],
    outputs: [quantity('item:machine-kit', 1)],
  }),

  resource({
    id: 'resource:fiber-plant',
    displayName: 'Fiber Plant',
    gatherChannelSeconds: 0.60,
    requiredToolItemId: null,
    output: quantity('item:plant-fiber', 2),
    maxGatherActions: 4,
    regenerationActiveSeconds: 600,
    toolConditionCostPerSuccessfulGather: 0,
  }),
  resource({
    id: 'resource:food-plant',
    displayName: 'Food Plant',
    gatherChannelSeconds: 0.60,
    requiredToolItemId: null,
    output: quantity('item:edible-plant', 1),
    maxGatherActions: 3,
    regenerationActiveSeconds: 900,
    toolConditionCostPerSuccessfulGather: 0,
  }),
  resource({
    id: 'resource:potable-water-source',
    displayName: 'Potable Water Source',
    gatherChannelSeconds: 0.60,
    requiredToolItemId: null,
    output: quantity('item:clean-water', 1),
    maxGatherActions: null,
    regenerationActiveSeconds: null,
    toolConditionCostPerSuccessfulGather: 0,
  }),
  resource({
    id: 'resource:timber-source',
    displayName: 'Timber Source',
    gatherChannelSeconds: 1,
    requiredToolItemId: 'item:stone-field-tool',
    output: quantity('item:timber', 1),
    maxGatherActions: 5,
    regenerationActiveSeconds: 1800,
    toolConditionCostPerSuccessfulGather: 2,
  }),
  resource({
    id: 'resource:stone-outcrop',
    displayName: 'Stone Outcrop',
    gatherChannelSeconds: 1,
    requiredToolItemId: 'item:stone-field-tool',
    output: quantity('item:stone', 2),
    maxGatherActions: 4,
    regenerationActiveSeconds: 1800,
    toolConditionCostPerSuccessfulGather: 2,
  }),
  resource({
    id: 'resource:metal-ore-node',
    displayName: 'Metal Ore Node',
    gatherChannelSeconds: 1,
    requiredToolItemId: 'item:stone-field-tool',
    output: quantity('item:metal-ore', 1),
    maxGatherActions: 6,
    regenerationActiveSeconds: 5400,
    toolConditionCostPerSuccessfulGather: 2,
  }),

  {
    id: 'entity:passive-wildlife',
    kind: 'entity',
    displayName: 'Passive Wildlife',
    role: 'passive-wildlife',
  },

  {
    id: 'structure:landing-module',
    kind: 'structure',
    displayName: 'Landing Module',
    sourceKitItemId: null,
    placeableByPlayer: false,
    phase1WorldCap: 1,
    roles: ['base-anchor', 'respawn-anchor'],
  },
  {
    id: 'structure:storage-crate',
    kind: 'structure',
    displayName: 'Storage Crate',
    sourceKitItemId: 'item:storage-crate-kit',
    placeableByPlayer: true,
    phase1WorldCap: 4,
    roles: ['shared-storage'],
    container: {
      maxWeightKg: 100,
      maxVolume: 120,
      acceptsAllPhase1PortableCategories: true,
      nestedContainersAllowed: false,
    },
  },
  {
    id: 'structure:workbench',
    kind: 'structure',
    displayName: 'Workbench',
    sourceKitItemId: 'item:workbench-kit',
    placeableByPlayer: true,
    phase1WorldCap: 1,
    roles: ['crafting-station'],
  },
  {
    id: 'structure:habitat-room',
    kind: 'structure',
    displayName: 'Habitat Room',
    sourceKitItemId: 'item:habitat-kit',
    placeableByPlayer: true,
    phase1WorldCap: 1,
    roles: ['base-anchor', 'shelter'],
    shelter: {
      thermalTarget: 50,
    },
  },
  {
    id: 'structure:compact-power-unit',
    kind: 'structure',
    displayName: 'Compact Power Unit',
    sourceKitItemId: 'item:power-unit-kit',
    placeableByPlayer: true,
    phase1WorldCap: 1,
    roles: ['power-source'],
    powerSource: {
      capacityPu: 10,
      radiusFootprints: 8,
      alwaysOn: true,
      consumesPortableFuel: false,
    },
  },
  {
    id: 'structure:atmospheric-water-condenser',
    kind: 'structure',
    displayName: 'Atmospheric Water Condenser',
    sourceKitItemId: 'item:machine-kit',
    placeableByPlayer: true,
    phase1WorldCap: 1,
    roles: ['machine-host'],
    machineDefinitionId: 'machine:atmospheric-water-condenser',
  },

  {
    id: 'machine:atmospheric-water-condenser',
    kind: 'machine',
    displayName: 'Atmospheric Water Condenser',
    powerDemandPu: 5,
    inputItems: [],
    outputItemId: 'item:clean-water',
    outputQuantityPerCycle: 1,
    cycleActivePoweredSeconds: 90,
    outputBufferCapacity: 4,
    supportsManualEnable: true,
    producesWhileAuthorityOffline: false,
    hasPeriodicWear: false,
  },

  {
    id: 'hazard:cold-exposure',
    kind: 'hazard',
    displayName: 'Cold Exposure',
    hazardType: 'cold-exposure',
    mitigationItemIds: ['item:thermal-wrap'],
    directHealthDamage: false,
  },
  {
    id: 'weather:cold-rain',
    kind: 'weather',
    displayName: 'Cold Rain',
    hazardIds: ['hazard:cold-exposure'],
    firstSessionStartWindowActiveMinutes: [28, 38],
    durationActiveSeconds: 360,
    warningSeconds: 60,
    dayThermalTarget: 30,
    nightThermalTarget: 20,
    changesPersistentFogKnowledge: false,
    directHealthDamage: false,
  },

  {
    id: 'hostile:territorial-predator',
    kind: 'hostile',
    displayName: 'Territorial Predator',
    maxHealth: 75,
    aggressionRadiusFootprints: 5,
    alertSeconds: 0.4,
    leashRadiusFootprints: 12,
    disengageOutsideSeconds: 2,
    attack: {
      rangeFootprints: 1.1,
      windupSeconds: 0.55,
      damage: 20,
      recoverySeconds: 1.2,
    },
    targetPolicy: 'nearest-valid-threatening-player',
    requiredUniqueDropItemId: null,
  },

  {
    id: 'ruin:previous-civilization-ruin',
    kind: 'ruin',
    displayName: 'Previous-Civilization Ruin',
    locateRadiusFootprints: 6,
    interaction: 'inspect',
    investigationIsImmediate: true,
    discoverySharedWithTeam: true,
    oneTimePhysicalReward: quantity('item:ancient-alloy-shard', 1),
    rewardRemainsClaimableIfInventoryFull: true,
  },

  {
    id: 'progression:phase1-early-progression',
    kind: 'progression',
    displayName: 'Phase 1 Early Progression',
    levelThresholds: [
      { level: 1, totalXpRequired: 0 },
      { level: 2, totalXpRequired: 100 },
      { level: 3, totalXpRequired: 225 },
      { level: 4, totalXpRequired: 400 },
      { level: 5, totalXpRequired: 650 },
    ],
    milestoneRules: [
      milestone(
        'first-gather:fiber-plant',
        { type: 'first-gather', resourceId: 'resource:fiber-plant' },
        8,
      ),
      milestone(
        'first-gather:food-plant',
        { type: 'first-gather', resourceId: 'resource:food-plant' },
        8,
      ),
      milestone(
        'first-gather:potable-water-source',
        { type: 'first-gather', resourceId: 'resource:potable-water-source' },
        8,
      ),
      milestone(
        'first-gather:timber-source',
        { type: 'first-gather', resourceId: 'resource:timber-source' },
        8,
      ),
      milestone(
        'first-gather:stone-outcrop',
        { type: 'first-gather', resourceId: 'resource:stone-outcrop' },
        8,
      ),
      milestone(
        'first-gather:metal-ore-node',
        { type: 'first-gather', resourceId: 'resource:metal-ore-node' },
        8,
      ),
      ...[
        'cordage',
        'stone-field-tool',
        'basic-spear',
        'thermal-wrap',
        'field-dressing',
        'storage-crate-kit',
        'workbench-kit',
        'repair-patch',
        'habitat-kit',
        'power-unit-kit',
        'machine-kit',
      ].map((slug) =>
        milestone(
          `first-craft:${slug}`,
          { type: 'first-craft', recipeId: `recipe:${slug}` },
          8,
        ),
      ),
      milestone(
        'first-condition-repair',
        { type: 'first-condition-repair' },
        12,
      ),
      milestone(
        'first-place:storage-crate',
        {
          type: 'first-structure-placement',
          structureId: 'structure:storage-crate',
        },
        15,
      ),
      milestone(
        'first-place:workbench',
        {
          type: 'first-structure-placement',
          structureId: 'structure:workbench',
        },
        20,
      ),
      milestone(
        'first-place:habitat-room',
        {
          type: 'first-structure-placement',
          structureId: 'structure:habitat-room',
        },
        30,
      ),
      milestone(
        'first-place:compact-power-unit',
        {
          type: 'first-structure-placement',
          structureId: 'structure:compact-power-unit',
        },
        25,
      ),
      milestone(
        'first-place:atmospheric-water-condenser',
        {
          type: 'first-structure-placement',
          structureId: 'structure:atmospheric-water-condenser',
        },
        35,
      ),
      milestone(
        'first-machine-output:clean-water',
        {
          type: 'first-machine-output-collect',
          machineId: 'machine:atmospheric-water-condenser',
          itemId: 'item:clean-water',
        },
        20,
      ),
      milestone(
        'first-expedition-band-entry',
        { type: 'first-expedition-band-entry' },
        20,
      ),
      milestone(
        'first-ruin-locate:previous-civilization-ruin',
        {
          type: 'first-ruin-locate',
          ruinId: 'ruin:previous-civilization-ruin',
        },
        30,
      ),
      milestone(
        'first-ruin-inspect:previous-civilization-ruin',
        {
          type: 'first-ruin-inspect',
          ruinId: 'ruin:previous-civilization-ruin',
        },
        100,
      ),
      milestone(
        'hostile-resolution:territorial-predator-base',
        {
          type: 'hostile-resolution',
          hostileId: 'hostile:territorial-predator',
        },
        20,
      ),
      milestone(
        'hostile-resolution:territorial-predator-kill-top-up',
        {
          type: 'hostile-resolution',
          hostileId: 'hostile:territorial-predator',
        },
        10,
      ),
      milestone(
        'first-own-death-cache-recovery',
        { type: 'first-own-death-cache-recovery' },
        15,
      ),
    ],
    repeatRules: [
      repeat('repeat:gather', 'gather', 2, 20),
      repeat('repeat:craft', 'craft', 2, 5),
      repeat('repeat:repair', 'repair', 4, 3),
    ],
    deathXpLoss: {
      percentCurrentLevelProgress: 5,
      minimumLossWhenProgressPositive: 1,
      mayReduceLevel: false,
    },
  },

  {
    id: 'skill:fieldcraft-basics',
    kind: 'skill',
    displayName: 'Fieldcraft Basics',
    requirements: [
      { type: 'minimum-level', level: 2 },
      { type: 'first-expedition-band-entry' },
    ],
    grantsPhase1StatModifier: false,
  },
  {
    id: 'skill:maintenance-basics',
    kind: 'skill',
    displayName: 'Maintenance Basics',
    requirements: [
      { type: 'minimum-level', level: 2 },
      { type: 'first-workbench-condition-repair' },
    ],
    grantsPhase1StatModifier: false,
  },

  {
    id: 'profession:explorer-prototype',
    kind: 'profession',
    displayName: 'Explorer — Prototype',
    prototypeOnly: true,
    exclusiveLock: false,
    grantsExclusiveCriticalPathCapability: false,
  },
  {
    id: 'profession:engineer-prototype',
    kind: 'profession',
    displayName: 'Engineer — Prototype',
    prototypeOnly: true,
    exclusiveLock: false,
    grantsExclusiveCriticalPathCapability: false,
  },

  {
    id: 'profession-quest:chart-the-unknown',
    kind: 'profession-quest',
    displayName: 'Chart the Unknown',
    minimumLevel: 3,
    requiredSkillId: 'skill:fieldcraft-basics',
    objectives: [
      {
        type: 'locate-ruin',
        ruinId: 'ruin:previous-civilization-ruin',
      },
      {
        type: 'inspect-ruin',
        ruinId: 'ruin:previous-civilization-ruin',
      },
      {
        type: 'return-alive-to-any-structure',
        structureIds: [
          'structure:landing-module',
          'structure:habitat-room',
        ],
      },
    ],
    rewardProfessionId: 'profession:explorer-prototype',
    rewardXp: 40,
  },
  {
    id: 'profession-quest:bring-water-online',
    kind: 'profession-quest',
    displayName: 'Bring Water Online',
    minimumLevel: 3,
    requiredSkillId: 'skill:maintenance-basics',
    objectives: [
      {
        type: 'structures-present',
        structureIds: [
          'structure:compact-power-unit',
          'structure:atmospheric-water-condenser',
        ],
      },
      {
        type: 'interact-powered-machine',
        machineId: 'machine:atmospheric-water-condenser',
      },
      {
        type: 'collect-machine-output',
        machineId: 'machine:atmospheric-water-condenser',
        itemId: 'item:clean-water',
        quantity: 1,
      },
    ],
    rewardProfessionId: 'profession:engineer-prototype',
    rewardXp: 40,
  },
];

export const PHASE1_CONTENT_PACK: ContentPackV1 = {
  formatId: CONTENT_FORMAT_ID,
  schemaVersion: CONTENT_SCHEMA_VERSION,
  packId: PHASE1_CONTENT_PACK_ID,
  packVersion: PHASE1_CONTENT_PACK_VERSION,
  definitions: DEFINITIONS,
};
